# Generated by Django 4.0.2 on 2022-02-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('device_type', models.CharField(max_length=255)),
                ('device_mac', models.CharField(max_length=255)),
                ('device_firmware_version', models.CharField(max_length=255)),
                ('device_software_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default=None, max_length=255, unique=True)),
                ('date_assigned', models.DateTimeField(verbose_name='Date Assigned')),
                ('associated_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('data_collected', models.IntegerField()),
                ('time_collected', models.DateTimeField(verbose_name='Date Collected')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_devices.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_devices.user')),
            ],
        ),
    ]
