# Generated by Django 4.0.2 on 2022-02-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
