# Generated by Django 4.0.2 on 2022-02-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_devices', '0002_remove_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
