# Generated by Django 4.0.2 on 2022-02-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_devices', '0003_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collection',
            name='device_type',
        ),
    ]
